# Generated by Django 3.2 on 2022-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='color',
        ),
        migrations.AddField(
            model_name='trackable',
            name='color',
            field=models.CharField(default='#fff', max_length=7),
            preserve_default=False,
        ),
    ]
