# Generated by Django 3.2 on 2023-01-07 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0002_auto_20220515_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackableValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('value', models.CharField(max_length=1024)),
                ('streak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streak.streak')),
            ],
        ),
    ]
