# Generated by Django 3.2 on 2023-01-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0003_trackablevalues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackableValues',
            new_name='TrackableValue',
        ),
    ]
