# Generated by Django 3.2 on 2023-01-07 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0004_rename_trackablevalues_trackablevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 4, 20, 27, 90202)),
        ),
    ]
